### ISSUE TITLE
Remove verification code page and add query parameter identification

### ISSUE THREAD

**Issue by michihupf** [darkdeltagaming/ddg-tournament-web#1]
Identity verification will happen via query parameter distributed by the bot. 

The parameter is a uuid that is mapped to the SteamID64 of the user. For testing purposes this uuid will equal the steam id. Once the backend has the API set up there will be another commit.

**Comment by oleggtro** [comment]
So actually the backend has nothing to do, but map random uuid to steamids and manage bans?

**Comment by michihupf** [comment]
And generate + transfer teams infornation (to website and plugin) and tournament leaderboard (to website)

**Comment by michihupf** [comment]
The verification code page is removed but there is no authentication as of now.

**Comment by michihupf** [comment]
Authentication is not needed for such a small project. Identification is using only the `uid` parameter now.

**Comment by oleggtro** [comment]
haha
